# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'DemoOffLineDBApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoOffLineDBApp
  pod 'FirebaseCore'
	pod 'FirebaseAuth'

  target 'DemoOffLineDBAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoOffLineDBAppUITests' do
    # Pods for testing
  end

end


post_install do |installer|
  # This disables sandboxing for the Pods project
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  # This disables sandboxing for your main App project
  installer.aggregate_targets.each do |target|
    target.user_project.targets.each do |user_target|
      user_target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    target.user_project.save
  end
end
